// <auto-generated />
using System;
using System.Collections.Generic;
using MedSecurance.DBAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedSecurance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250424165903_AddActivityLogUserFullNameColumn")]
    partial class AddActivityLogUserFullNameColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedSecurance.ActivityLog.Models.ActivityLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogsEntity");
                });

            modelBuilder.Entity("MedSecurance.DeviceManager.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BatteryStatus")
                        .HasColumnType("integer");

                    b.Property<int>("CommunicationProtocol")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DoctorId")
                        .HasColumnType("text");

                    b.Property<int?>("Location")
                        .HasColumnType("integer");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ManufacturingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NetworkIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("NetworkName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("StandardCompliance")
                        .HasColumnType("boolean");

                    b.Property<int[]>("SupportedCommunicationProtocols")
                        .HasColumnType("integer[]");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Validated")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("MedSecurance.ProtocolEvaluator.Configuration.AdminConfig", b =>
                {
                    b.Property<string>("Property")
                        .HasColumnType("text");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Property", "Protocol");

                    b.ToTable("AdminConfigs");

                    b.HasData(
                        new
                        {
                            Property = "MeanTimeToRepairInMinutes",
                            Protocol = 0,
                            Value = "5"
                        },
                        new
                        {
                            Property = "MeanDowntimeInMinutes",
                            Protocol = 0,
                            Value = "30"
                        },
                        new
                        {
                            Property = "LifetimeInYears",
                            Protocol = 0,
                            Value = "24"
                        },
                        new
                        {
                            Property = "MeanTimeToRepairInMinutes",
                            Protocol = 1,
                            Value = "5"
                        },
                        new
                        {
                            Property = "MeanDowntimeInMinutes",
                            Protocol = 1,
                            Value = "30"
                        },
                        new
                        {
                            Property = "LifetimeInYears",
                            Protocol = 1,
                            Value = "10"
                        },
                        new
                        {
                            Property = "MeanTimeToRepairInMinutes",
                            Protocol = 2,
                            Value = "5"
                        },
                        new
                        {
                            Property = "MeanDowntimeInMinutes",
                            Protocol = 2,
                            Value = "30"
                        },
                        new
                        {
                            Property = "LifetimeInYears",
                            Protocol = 2,
                            Value = "10"
                        },
                        new
                        {
                            Property = "MeanTimeToRepairInMinutes",
                            Protocol = 3,
                            Value = "5"
                        },
                        new
                        {
                            Property = "MeanDowntimeInMinutes",
                            Protocol = 3,
                            Value = "30"
                        },
                        new
                        {
                            Property = "LifetimeInYears",
                            Protocol = 3,
                            Value = "10"
                        });
                });

            modelBuilder.Entity("MedSecurance.ProtocolEvaluator.Models.RiskAssessment.RiskAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NetworkName")
                        .HasColumnType("text");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RiskAssessments");
                });

            modelBuilder.Entity("MedSecurance.DeviceManager.Models.Device", b =>
                {
                    b.OwnsOne("MedSecurance.DeviceManager.Models.BluetoothDevice", "BluetoothSpecs", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Bandwidth")
                                .HasColumnType("integer");

                            b1.Property<string>("Firmware")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("FirmwareDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("MacAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int[]>("SupportedAccessControlMechanisms")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.Property<int[]>("SupportedAntenas")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.Property<int[]>("SupportedAuthenticationMethods")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.Property<int[]>("SupportedDataIntegrities")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.Property<int[]>("SupportedTopologies")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.Property<List<decimal>>("SupportedVersions")
                                .IsRequired()
                                .HasColumnType("numeric[]");

                            b1.Property<int>("UtilizedAccessControlMechanism")
                                .HasColumnType("integer");

                            b1.Property<int>("UtilizedAntena")
                                .HasColumnType("integer");

                            b1.Property<int>("UtilizedAuthenticationMethod")
                                .HasColumnType("integer");

                            b1.Property<int>("UtilizedDataIntegrity")
                                .HasColumnType("integer");

                            b1.Property<int>("UtilizedTopology")
                                .HasColumnType("integer");

                            b1.Property<decimal>("UtilizedVersion")
                                .HasColumnType("numeric");

                            b1.HasKey("DeviceId");

                            b1.ToTable("BluetoothDevices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.OwnsOne("MedSecurance.DeviceManager.Models.GsmDevice", "GsmSpecs", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Bandwidth")
                                .HasColumnType("integer");

                            b1.Property<string>("Firmware")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("FirmwareDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("MacAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int[]>("SupportedGenerations")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.Property<int>("UtilizedGeneration")
                                .HasColumnType("integer");

                            b1.HasKey("DeviceId");

                            b1.ToTable("GsmDevices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.OwnsOne("MedSecurance.DeviceManager.Models.LorawanDevice", "LorawanSpecs", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AdaptiveDataRate")
                                .HasColumnType("boolean");

                            b1.Property<int>("Bandwidth")
                                .HasColumnType("integer");

                            b1.Property<string>("Firmware")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("FirmwareDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("JoinMode")
                                .HasColumnType("integer");

                            b1.Property<string>("MacAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("PhysicalLocation")
                                .HasColumnType("integer");

                            b1.Property<int[]>("SupportedFrequencyBands")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.Property<int>("UtilizedFrequencyBand")
                                .HasColumnType("integer");

                            b1.HasKey("DeviceId");

                            b1.ToTable("LorawanDevices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.OwnsOne("MedSecurance.DeviceManager.Models.WifiDevice", "WifiSpecs", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Bandwidth")
                                .HasColumnType("integer");

                            b1.Property<int>("Encryption")
                                .HasColumnType("integer");

                            b1.Property<string>("Firmware")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("FirmwareDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("FrequencyUtilized")
                                .HasColumnType("integer");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("MacAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("StandardUtilized")
                                .HasColumnType("integer");

                            b1.Property<int[]>("SupportedFrequencies")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.Property<int[]>("SupportedStandards")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.HasKey("DeviceId");

                            b1.ToTable("WifiDevices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.Navigation("BluetoothSpecs");

                    b.Navigation("GsmSpecs");

                    b.Navigation("LorawanSpecs");

                    b.Navigation("WifiSpecs");
                });
#pragma warning restore 612, 618
        }
    }
}
