services:
  monitor-matrix:
    network_mode: "host"
    build: 
      context: ./
      dockerfile: Dockerfile
      args:
        MEDSEC_URL: ${MEDSEC_URL}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        UPDATE_DELAY_MINUTES: ${UPDATE_DELAY_MINUTES}
        EMAIL_DELAY_DAYS: ${EMAIL_DELAY_DAYS}
    container_name: medsec-monitor-matrix
    volumes:
      - user-data:/app/user-data

volumes:
  user-data: